# Generated by Django 4.2.5 on 2023-12-19 19:52

import catalog.models
import catalog.validators
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'region',
                    models.CharField(
                        help_text='Введите регион',
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name='регион',
                    ),
                ),
            ],
            options={
                'verbose_name': 'регион',
                'verbose_name_plural': 'регионы',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите название',
                        max_length=150,
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name='название',
                    ),
                ),
                (
                    'text',
                    ckeditor.fields.RichTextField(
                        help_text='Введите описание',
                        validators=[
                            catalog.validators.MaxWordsValidator(1000)
                        ],
                        verbose_name='Текст',
                    ),
                ),
                (
                    'lat',
                    models.FloatField(
                        help_text='Введите широту', verbose_name='широта'
                    ),
                ),
                (
                    'lon',
                    models.FloatField(
                        help_text='Введите долготу', verbose_name='долгота'
                    ),
                ),
                (
                    'date_created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата создания места'
                    ),
                ),
                (
                    'status_free',
                    models.BooleanField(null=True, verbose_name='платное'),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=False, null=True, verbose_name='активный'
                    ),
                ),
                (
                    'region',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text='Выберите или добавьте регион',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='spot_region',
                        related_query_name='spot_region',
                        to='catalog.region',
                        verbose_name='Регион',
                    ),
                ),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
                'ordering': ('region',),
            },
        ),
        migrations.CreateModel(
            name='SpotMainImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to=catalog.models.SpotMainImage.upload_to,
                        verbose_name='изображение',
                    ),
                ),
                (
                    'spot',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='spot_mainimage',
                        related_query_name='spot_mainimage',
                        to='catalog.spot',
                        verbose_name='озеро',
                    ),
                ),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.CreateModel(
            name='SpotImages',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=catalog.models.SpotImages.upload_to,
                        verbose_name='изображение',
                    ),
                ),
                (
                    'spot',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='spot_images',
                        related_query_name='spot_images',
                        to='catalog.spot',
                        verbose_name='товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'изображения',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
