# Generated by Django 4.2.5 on 2024-01-02 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_user_options'),
        ('users', '0002_alter_user_options_alter_user_location'),
    ]

    operations = []
